### ISSUE TITLE
First issue ! hahaha!

### ISSUE THREAD

**Issue by twinfishxixi** [CN1984/LearningThePooh#1]
I have read all the code, from the point of view of the scoring method, the idea of ​​directly performing the score statistics is Really Great!
It is completely possible to ignore that three double integration time periods.

**Anytime Anywhere, You Can Learning!** Oh Yeah!~

**Comment by CN1984** [comment]
Yep, it's an efficient solution when I find the difference between 'normal time' and 'hot time' just the number of scores.
