### ISSUE TITLE
market

### ISSUE THREAD

**Issue by noway2014** [CN1984/LearningThePooh#10]
firefox可以使用吗

**Comment by CN1984** [comment]
> firefox可以使用吗

I tested it on the latest version of Firefox and can't running. Don't know if on the old version.

**Comment by solo052** [comment]
谢谢 大神的小熊。。请问阅读的时间是随机的吗。随机的话可以减少点风险

**Comment by CN1984** [comment]
> 谢谢 大神的小熊。。请问阅读的时间是随机的吗。随机的话可以减少点风险

Duplicate of #4

**Comment by noway2014** [comment]
look at here,
https://github.com/hsfzxjy/xxqg-addon/issues/5

**Comment by CN1984** [comment]
> 你的快速模式能否像这样一种思路？look at here,
> [hsfzxjy/xxqg-addon#5](https://github.com/hsfzxjy/xxqg-addon/issues/5)
> 
> 另外，手机运行火狐可以运行脚本，而手机的chrome则不可以。所以火狐还有优势，希望能考虑下

Modifying the official code will easy to be detect. I recommend speeding up by simulating human behavior, just like opening multiple windows. Because safety is the most important for this tool.

Thanks your information. Currently no plan to compatible with mobile device. May be later : )

**Comment by CN1984** [comment]
@noway2014 
Here's a key question about mobile devices: 
How to use the official APP to scan the qrcode from login page on firefox mobile.

**Comment by noway2014** [comment]
可以使用两台手机，或者拍照下来，在那个软件中扫描。手机因为随时呆在身上，这个的firefox版本很有用，因为只有firefox手机版本才可以运行扩展………

**Comment by lls1043** [comment]
非常感谢，想学习的时候自己看，时间来不及就用小熊。辛苦了！

**Comment by noway2014** [comment]
看到新加了firefox支持，感谢作者，但是不知道手机firefox如何导入安装？

**Comment by noway2014** [comment]
安卓手机firefox安装后，浏览器出现图标，点击无法后当前页面没有反应…

**Comment by CN1984** [comment]
> 安卓手机firefox安装后，浏览器出现图标，点击图标后，当前页面没有反应…
> 是否再参考下这个https://github.com/hsfzxjy/xxqg-addon
> 它是在页面中出现按钮，点击使用的，chorme和火狐都可以。

Have a try the new v1.3.3, that is fully support Firefox Mobile [Firefox Add-ons](https://addons.mozilla.org/zh-CN/firefox/addon/%E5%AD%A6%E4%B9%A0%E5%B0%8F%E7%86%8A).

I think that is a dangerous practice. Not to change anything on the page is my aim.

**Comment by noway2014** [comment]
where can download1.3.3

**Comment by solo052** [comment]
安全第一，不要搞太多东西了

**Comment by noway2014** [comment]
请问，快速模式大概原理？是否容易别识别？觉得正常有些慢

**Comment by CN1984** [comment]
> 请问，快速模式大概原理？是否容易别识别？觉得正常有些慢

'Flash Mode' is almost like 'Safe Mode' but multi-window. I'm not sure multi-window isn't cheating.

**Comment by noway2014** [comment]
如果正常网页登陆，不使用插件情况下，多窗口浏览，是正常的，不算。

**Comment by noway2014** [comment]
手机firefox使用能支持真的很方便。感谢。
因为手机的chrome不支持扩展，而手机携带方便…希望维护下去…再次感谢

**Comment by f20190610** [comment]
安装Firefox Mobile Firefox Add-ons.最新版，用钉钉帐号登陆，帐号、密码没有输错，提示“号码或密码错误，请重新输入”是什么原因？
