### ISSUE TITLE
建议让文章的选择更人性化

### ISSUE THREAD

**Issue by listenfree** [CN1984/LearningThePooh#12]
目前看来，好象是随机选的文章来阅读，反人类，应该在首页，或在页面里选有的链接跳转，而不是生硬的直接跳。
感谢程主的辛勤劳动。

**Comment by CN1984** [comment]
> 目前看来，好象是随机选的文章来阅读，反人类，应该在首页，或在页面里选有的链接跳转，而不是生硬的直接跳。
> 感谢程主的辛勤劳动。

All links are taken from the homepage.

**Comment by listenfree** [comment]
但是只是从dataindex.js里来的，不是页面上正常的，谁会硬生生的去访问一个很久以前的新闻页面，只是建议哈，这样才能更不容易被查觉

**Comment by candyl6** [comment]
同感，这几天发现看的文章都好旧

**Comment by CN1984** [comment]
Duplicate of #28
