### ISSUE TITLE
能否增加账号密码登录？

### ISSUE THREAD

**Issue by leyan22** [CN1984/LearningThePooh#13]
隔壁的有这个功能，但觉得还是浏览器插件方便，希望能增加账号密码登录，这样手机就不用下载了！有时候还可以帮家里人挂挂！

**Comment by CN1984** [comment]
Website version does not support password login.

**Comment by solo052** [comment]
> 隔壁的有这个功能，但觉得还是浏览器插件方便，希望能增加账号密码登录，这样手机就不用下载了！有时候还可以帮家里人挂挂！

隔壁的安全吗  给个链接看看

**Comment by ksky521** [comment]
@CN1984 没细研究，但是猜测可以通过修改 useragent 和拦截接口获取 token 等方式完成密码登录

**Comment by xjy1995** [comment]
@CN1984 Please consider adding support for dingtalk login. The URL is attached below.
https://login.dingtalk.com/login/index.htm?goto=https%3A%2F%2Foapi.dingtalk.com%2Fconnect%2Foauth2%2Fsns_authorize%3Fappid%3Ddingoankubyrfkttorhpou%26response_type%3Dcode%26scope%3Dsnsapi_login%26redirect_uri%3Dhttps%3A%2F%2Fpc-api.xuexi.cn%2Fopen%2Fapi%2Fsns%2Fcallback

**Comment by CN1984** [comment]
@xjy1995 thx your info. test later...

**Comment by CN1984** [comment]
@leyan22 @xjy1995 have a try [v1.3.9](https://github.com/CN1984/LearningThePooh/releases/tag/v1.3.9)

**Comment by ksky521** [comment]
好像账号登陆又不行了
