### ISSUE TITLE
1.34新版无法继续学习…

### ISSUE THREAD

**Issue by noway2014** [CN1984/LearningThePooh#16]
手机安卓firefox昨天更新成1.34版本，安装后，在浏览器点击图标，无法激活学习…

**Comment by lizuolong** [comment]
网站更新了导致的

**Comment by lvtutu1900** [comment]
小熊打不开了，点击没有反应

**Comment by LevineWoo** [comment]
网站更新，不能获取分数和看文章视频了。

**Comment by menshiyun** [comment]
PR已修复 #17

**Comment by lizuolong** [comment]
> PR已修复 #17

跟我修改的一样，已经学完了，不知道还有没有暗装

**Comment by CN1984** [comment]
Store has been updated to [v1.3.5](https://github.com/CN1984/LearningThePooh/releases/tag/v1.3.5).

**Comment by xieweiworld** [comment]
最新的版本也没法继续学习了
