### ISSUE TITLE
今天点击插件发现没有跳出新窗口了嘛

### ISSUE THREAD

**Issue by tuzizha** [CN1984/LearningThePooh#19]
好像前几天都能用的

**Comment by Random-Jack** [comment]
阿里爸爸这是在下一盘很大的棋啊。
最近各浏览器好像都不能用了，低调的人都在刷着自己的脚本。O(∩_∩)O哈哈~

**Comment by CN1984** [comment]
> 好像前几天都能用的

Have a try the latest version

**Comment by solo052** [comment]
1.3.5可以用了，

**Comment by tuzizha** [comment]
对，确认了，1.3.5可以用。谢谢。幸苦了。

**Comment by CN1984** [comment]
Duplicate of #16
