### ISSUE TITLE
看视频有个办法可以节省4/5时间

### ISSUE THREAD

**Issue by nnkn** [CN1984/LearningThePooh#2]
同时开5个窗口看视频就可以了，不过5个窗口都要露出来

**Comment by CN1984** [comment]
Thanks for your suggestion, but, how to balance between safety and speed is a question that needs to be considered. May be add an option to the user next time.

**Comment by ddkk3000** [comment]
app的题能做吗？

**Comment by CN1984** [comment]
> app的题能做吗？

Unfortunately, only support the website version currently.

**Comment by nnkn** [comment]
> Thanks for your suggestion, but, how to balance between safety and speed is a question that needs to be considered. May be add an option to the user next time.

感谢！！

**Comment by wangwangyh** [comment]
@CN1984 Thanks for your software that is perfectly suitable for Macbook.

**Comment by CN1984** [comment]
> 同时开5个窗口看视频就可以了，不过5个窗口都要露出来

I had tried to use multi-window, but did not earn points in the same time when watch time longer than video duration. Can you give me more information?

**Comment by kirbybear** [comment]
I achieved acceleration by using multiple shell.explorer activeX controls to open diffrent article/video pages simultaneously and randomly scrolling them. 

For more, the activeX control windows can be hidden into bg without interfere any normal usage, and score points still accumulate. Idk if chrome could accelerate the process in the same way...

The whole process would be completed in 5 to 15 minutes depends on hardware performance, number of threads and double time.

![7187b36bbf5791a1dac74ffec2c5669](https://user-images.githubusercontent.com/2975851/54824448-eb468580-4ce5-11e9-9dd3-1027c3d95ee3.jpg)

**Comment by CN1984** [comment]
> I achieved acceleration by using multiple shell.explorer activeX controls to open diffrent article/video pages simultaneously and randomly scrolling them.
> 
> For more, the activeX control windows can be hidden into bg without interfere any normal usage, and score points still accumulate. Idk if chrome could accelerate the process in the same way...
> 
> The whole process would be completed in 5 to 15 minutes depends on hardware performance, number of threads and double time.
> 
> ![7187b36bbf5791a1dac74ffec2c5669](https://user-images.githubusercontent.com/2975851/54824448-eb468580-4ce5-11e9-9dd3-1027c3d95ee3.jpg)

Thank you for the information. Maybe there are less constraints on IE than modern browsers. XD

But fortunately I have found a solution now, just need more tests to confirm it.

**Comment by CN1984** [comment]
@nnkn @ahe-meow 
Please test the new version [v1.3.0](https://github.com/CN1984/LearningThePooh/releases/tag/v1.3.0). 
Waiting your feedback.

**Comment by nnkn** [comment]
I have  completed the study today and I will test  it tomorrow, thankyou very  much!
@CN1984

**Comment by nnkn** [comment]
> @nnkn @ahe-meow
> Please test the new version [v1.3.0](https://github.com/CN1984/LearningThePooh/releases/tag/v1.3.0).
> Waiting your feedback.

I have completed the study today and I will test it tomorrow, thankyou very much!
@CN1984

**Comment by nnkn** [comment]
> @nnkn @ahe-meow
> Please test the new version [v1.3.0](https://github.com/CN1984/LearningThePooh/releases/tag/v1.3.0).
> Waiting your feedback.

![pic](https://user-images.githubusercontent.com/22342244/55283415-3bcc7b80-5395-11e9-9f1a-d48028d89c44.jpg)
