### ISSUE TITLE
Please be vigilant recently

### ISSUE THREAD

**Issue by CN1984** [CN1984/LearningThePooh#20]
There is new score API response:
![api response](https://user-images.githubusercontent.com/47753275/56016077-bc905d80-5d2d-11e9-91ff-bcbc1b3f19f7.png)

We can find that some important info have been added: `ruleId: 2003` `blackListTip` `inBlackList` . Perhaps the anti-cheating operations is going on.

If there is any new situation, please let us know here.

**Comment by oppoic** [comment]
horrible, pls pinned this issue.

**Comment by lizuolong** [comment]
好像视频不播放了

**Comment by CN1984** [comment]
> 好像视频不播放了

Because I deleted the code that forces autoplay.
If you still can get points, don't care about it.

**Comment by dang1013** [comment]
one sound?oh my god.for a whole mouth!whats the concrete rules?

**Comment by dang1013** [comment]
one thousand?my god!a whole month.
and whats the concrete rules?
