### ISSUE TITLE
1.3.5出现CRX_HEADER_INVALID

### ISSUE THREAD

**Issue by zogvm** [CN1984/LearningThePooh#21]
1.3.5装谷歌浏览器出现CRX_HEADER_INVALID

**Comment by jankingfly** [comment]
直接去插件商场装就可以了

**Comment by CN1984** [comment]
> 1.3.5装谷歌浏览器出现CRX_HEADER_INVALID

Try to download the `release` folder, enter chrome://extensions/ in the browser address bar, check Developer mode -> Load unpacked extension, navigate to the `release` folder.
