### ISSUE TITLE
忽然失灵了

### ISSUE THREAD

**Issue by jankingfly** [CN1984/LearningThePooh#22]
以前一直是正常的，今天登陆后缩小的窗口仍旧出现，不过两个滚动条不再滚动，而且分数也没有增加，又被封了吗

**Comment by XueTeng2** [comment]
可能是因为升级的原因。

**Comment by jankingfly** [comment]
什么升级？网站升级吗？   那插件会同步升级吗

2019-04-15 

janking 



发件人：XueTeng2 <notifications@github.com>
发送时间：2019-04-15 21:08
主题：Re: [CN1984/LearningThePooh] 忽然失灵了 (#22)
收件人："CN1984/LearningThePooh"<LearningThePooh@noreply.github.com>
抄送："jankingfly"<janking@126.com>,"Author"<author@noreply.github.com>

可能是因为升级的原因。

**Comment by CN1984** [comment]
> 以前一直是正常的，今天登陆后缩小的窗口仍旧出现，不过两个滚动条不再滚动，而且分数也没有增加，又被封了吗

What browser do you using?

**Comment by Kaede008** [comment]
chrome最新版 安全模式和闪电模式都试过 确实只有小窗口 滚动条不滚动 分数亦不增加.

**Comment by noway2014** [comment]
firefox 也手机版是这个问题

**Comment by jankingfly** [comment]
chrome

2019-04-16 

janking 



发件人：CN1984 <notifications@github.com>
发送时间：2019-04-15 22:25
主题：Re: [CN1984/LearningThePooh] 忽然失灵了 (#22)
收件人："CN1984/LearningThePooh"<LearningThePooh@noreply.github.com>
抄送："jankingfly"<janking@126.com>,"Author"<author@noreply.github.com>

以前一直是正常的，今天登陆后缩小的窗口仍旧出现，不过两个滚动条不再滚动，而且分数也没有增加，又被封了吗
What browser do you using?

**Comment by jankingfly** [comment]
我用的也是 Chrome 失灵了

**Comment by LevineWoo** [comment]
突然不能用+1

**Comment by fengwolf3** [comment]
确实现在不能动了，小窗有出来，但是没办法滚动和加分，麻烦帮忙更新，非常感谢。

**Comment by tq036my** [comment]
升级好快，又不行了，老大教我们怎么自己更新呢？

**Comment by LevineWoo** [comment]
> 升级好快，又不行了，老大教我们怎么自己更新呢？

是学习强国服务器更新哦。

**Comment by CN1984** [comment]
let me see

**Comment by CN1984** [comment]
dataindex.js from homepage have been remove.

**Comment by BBKoop** [comment]
> dataindex.js from homepage have been remove.

期待1.3.6版本

**Comment by CN1984** [comment]
[v1.3.6](https://github.com/CN1984/LearningThePooh/releases/tag/v1.3.6)

**Comment by oldplane001** [comment]
感谢大神

**Comment by kisy19** [comment]
Thank you for sharing. The software works well.
