### ISSUE TITLE
2019.4.17 11:35 提示无有效链接，只显示分数不刷文章

### ISSUE THREAD

**Issue by LevineWoo** [CN1984/LearningThePooh#25]
2019.4.17 11:35 右下角弹出chrome提示无有效链接，只显示分数不刷文章
版本：1.3.6

**Comment by lizuolong** [comment]
正常呀，我的现在还在用呢

**Comment by CN1984** [comment]
> 2019.4.17 11:35 右下角弹出chrome提示无有效链接，只显示分数不刷文章
> 版本：1.3.6

Do you use multiple accounts in the same browser?

**Comment by LevineWoo** [comment]
> > 2019.4.17 11:35 右下角弹出chrome提示无有效链接，只显示分数不刷文章
> > 版本：1.3.6
> 
> ‘No available link’ means all links from index have been used one times.
> Do you use multiple accounts in the same browser?

是的，一天需要挂2个号。

**Comment by CN1984** [comment]
Fix this issue on the coming release.

**Comment by LevineWoo** [comment]
> Fix this issue on the coming release.

thx :)

**Comment by lizuolong** [comment]
可以清空cookie试试

**Comment by noway2014** [comment]
能否开两个浏览器，同一个账户进行学习，以加快速度？

**Comment by CN1984** [comment]
@LevineWoo Have try [v1.3.8](https://github.com/CN1984/LearningThePooh/releases/tag/v1.3.8)

@noway2014 Why not use flash mode?

**Comment by noway2014** [comment]
你说不安全嘛

**Comment by noway2014** [comment]
yendex can use chrome plus…
