### ISSUE TITLE
看了一篇1998年的文章，有点怕怕

### ISSUE THREAD

**Issue by nssiwi** [CN1984/LearningThePooh#28]
发现插件浏览的很多是非常老的文章了，还有10年的

**Comment by CN1984** [comment]
Take is easy. It's not a bug. 

Homepage isn't only have news. e.g. there are some 'old article' in the 'Red china' section.

You can find an [article in 1952].(https://www.xuexi.cn/861a8fe9c52611e55d9b55b0445a48c8/78f3c481f718d5d57806ee36108ac82c.html?p1=%E9%BB%84%E7%BB%A7%E5%85%89%E7%B2%BE%E7%A5%9E) earlier than the Internet. 😄

**Comment by noway2014** [comment]
我觉得抢分，利用漏洞，加快速度这种才叫违规，随便点网站，看各个时期文章哪可以叫违规？
