### ISSUE TITLE
would you give email or qq to me？

### ISSUE THREAD

**Issue by szmsys** [CN1984/LearningThePooh#29]
would you give email or qq to me？

I have one question.

thank you！

**Comment by kgmxxfz** [comment]
ok




 
---Original---

**Comment by kgmxxfz** [comment]
1062739318@qq.com

**Comment by kgmxxfz** [comment]
who are you?

**Comment by nssiwi** [comment]
what question?

**Comment by CN1984** [comment]
😂... just show your question here.
