### ISSUE TITLE
fitefox插件库下架了吗？今天突然不能用了！[BUG]

### ISSUE THREAD

**Issue by dang1013** [CN1984/LearningThePooh#30]
**Describe the bug**

**Device (please complete the following information):**
 - OS: [e.g. Windows 10, iOS8.1]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. v1.3.5, v1.3.6]

**Comment by oppoic** [comment]
see this：[https://www.v2ex.com/t/560803](url)
