### ISSUE TITLE
i do not work now

### ISSUE THREAD

**Issue by jankingfly** [CN1984/LearningThePooh#35]
plz check it

**Comment by nssiwi** [comment]
> plz check it

mine still works

**Comment by jankingfly** [comment]
when i restart my computer,i seems ok


2019-05-13 

janking 



发件人：John <notifications@github.com>
发送时间：2019-05-12 21:07
主题：Re: [CN1984/LearningThePooh] i do not work now (#35)
收件人："CN1984/LearningThePooh"<LearningThePooh@noreply.github.com>
抄送："jankingfly"<janking@126.com>,"Author"<author@noreply.github.com>

plz check it
mine still works
