### ISSUE TITLE
如何实现输入账号密码登录？

### ISSUE THREAD

**Issue by leyan22** [CN1984/LearningThePooh#36]
看介绍1.3.9版本增加了这个功能，我今天下载的1.3.11版本，似乎还是只有二维码入口？

**Comment by leyan22** [comment]
另外用chrome怎么样也刷不出登录二维码，反而QQ浏览器可以！

**Comment by CN1984** [comment]
Right click on the `pooh` icon, select `Login by account` in the menu.

**Comment by allenf2005** [comment]
我是新注册的学习强国，发现用二维码扫描进入的和用账号密码登录进入的不是同个账号，看了下登录界面，似乎有个账号是钉钉同步的，有个是学习强国内注册的？

**Comment by leyan22** [comment]
> Right click on the `pooh` icon, select `Login by account` in the menu.

QQ浏览器貌似没法使用右键这个功能

**Comment by noway2014** [comment]
楼上qq浏览器这么毒也敢用？

**Comment by CN1984** [comment]
Got it, may be fixed in the next version.

**Comment by FLASH023** [comment]
早期 强国和钉钉是相同的账号
后来独立了
现在也可以用钉钉登陆强国（这是个bug） 但是这个id只能用钉钉登陆 不能用强国登陆

 

这个浏览器插件还不够智能化
强强  仍然可以轻松封掉它

**Comment by CN1984** [comment]
Try new version v1.4.4
