### ISSUE TITLE
建议增加模拟人工操作

### ISSUE THREAD

**Issue by elleys** [CN1984/LearningThePooh#4]
1、随机移动鼠标和滚轮
2、鼠标移动时间触发随机但不超过3min
3、阅读/观看时长更加凌乱化。

**Comment by CN1984** [comment]
> 1、随机移动鼠标和滚轮
> 2、鼠标移动时间触发随机但不超过3min
> 3、阅读/观看时长更加凌乱化。

- Sorry, chome extension haven't any API about mouse
- Reading time is 30s to 1min already looks like human operation. What is your suggestion?

**Comment by elleys** [comment]
> > 1、随机移动鼠标和滚轮
> > 2、鼠标移动时间触发随机但不超过3min
> > 3、阅读/观看时长更加凌乱化。
> 
> * Sorry, chome extension haven't any API about mouse
> * Reading time is 30s to 1min already looks like human operation. What is your suggestion?

that's ok ~less 2min is looks like human behavior,and maybe we can check empty place

**Comment by CN1984** [comment]
Have a try the new release [v1.2.6](https://github.com/CN1984/LearningThePooh/releases/tag/v1.2.6)
