### ISSUE TITLE
6.2号开始不能自动切换到视频学习了

### ISSUE THREAD

**Issue by yyx3658** [CN1984/LearningThePooh#40]
学完文字之后，第一个视频就停下来，反复用安全模式、闪电模式测试，问题依旧，系统环境不变：win10 centbrowser 4.09

**Comment by LevineWoo** [comment]
chrome   74.0.3729.169目前没发现这个情况，用的是账号密码登录模式。

**Comment by yyx3658** [comment]
感谢回复，我也切了 账号密码模式，再试几天看看。感谢作者设计这么方便的软件！




------------------ 原始邮件 ------------------
发件人: "&#x259;u&#x131;&#x28C;&#x259;l"<notifications@github.com>; 
发送时间: 2019年6月3日(星期一) 上午9:36
收件人: "CN1984/LearningThePooh"<LearningThePooh@noreply.github.com>; 
抄送: "/mn^将狼踩尽"<83385494@QQ.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CN1984/LearningThePooh] 6.2号开始不能自动切换到视频学习了 (#40)




chrome   74.0.3729.169目前没发现这个情况，用的是账号密码登录模式。

**Comment by CN1984** [comment]
this issue only based on login by QR Code？

**Comment by nssiwi** [comment]
> this issue only based on login by QR Code？

probably yes, i tried login by dingding , it works well

**Comment by LevineWoo** [comment]
> this issue only based on login by QR Code？

QR Code is OK too.

**Comment by nssiwi** [comment]
> > this issue only based on login by QR Code？
> 
> QR Code is OK too.

for me, QR Code can not get all the 24 scores, sometimes 23 or little.

**Comment by CN1984** [comment]
@yyx3658 @nssiwi try version [v1.4.1](https://github.com/CN1984/LearningThePooh/releases/tag/v1.4.1)

**Comment by f20190610** [comment]
希望增加学习随机时长（学完一篇文章或视频，随机延时一段时间，然后学习下一个任务），每篇文章貌似都卡着时间学习的，到点立马切换到下一篇，这样很容易被检测到刷分，而且程序学习完立马就退出（最好是延时退出）。刚刚使用LearningThePooh，具体使用方法还不太明白。如果有不当之处请见谅。

**Comment by CN1984** [comment]
> 希望增加学习随机时长（学完一篇文章或视频，随机延时一段时间，然后学习下一个任务），每篇文章貌似都卡着时间学习的，到点立马切换到下一篇，这样很容易被检测到刷分，而且程序学习完立马就退出（最好是延时退出）。刚刚使用LearningThePooh，具体使用方法还不太明白。如果有不当之处请见谅。

Duplicate of #4
