### ISSUE TITLE
[BUG]学习文章时长经常不增加

### ISSUE THREAD

**Issue by xuxudong1110** [CN1984/LearningThePooh#43]
火狐。谷歌二种浏览器视频学习没问题，文章学习的时候数量能学满，学习时间却一直不加。

**Comment by CN1984** [comment]
Maybe the rules have changed, test later.
Is there anyone else like this?

**Comment by nssiwi** [comment]
> Maybe the rules have changed, test later.
> Is there anyone else like this?

met this problem when login by dingding

**Comment by CN1984** [comment]
@xuxudong1110 @nssiwi 
Maybe it's a official issue...  I find that increase video's points when read article.

**Comment by nickwzy** [comment]
same issue, other projects mentioned 'a-log' need to be modified.

**Comment by nickwzy** [comment]
The issue could be temporary solved by opening a xuexi.cn page in the same explorer.

**Comment by mybottlemycolor** [comment]
> same issue, other projects mentioned 'a-log' need to be modified.
please check this ，will u update it？
https://github.com/Alivon/Panda-Learning/issues/403

**Comment by CN1984** [comment]
Yep, I have learned about the situation from another project. But that‘s a incomplete solution. 
If you wanted it in this project, easy to do:
Edit the `js/background.js` , delete the code by line number: 17-24 and 26-40.
That means just keep `"u1ght1omn2|https://...html",` in the channel.article.

I am still looking for a better solution, then push new version.

**Comment by alldiy** [comment]
2019年6月18日出现了同样的问题，文章时常不增加。 之前出现过视频时长不增加，但重新登录后就好，而本次文章时常不增加的问题，重新登录也无法解决

**Comment by CN1984** [comment]
Try new version v1.4.2
