### ISSUE TITLE
经常打开同一篇文章在看，看完也不增长分数[BUG]

### ISSUE THREAD

**Issue by hcketw** [CN1984/LearningThePooh#46]
经常打开同一篇文章在看，自动滑动到下面，看完也不增长分数。可能是同一篇文章只能增长一次分数。

**Comment by pangump** [comment]
每次只能拿23分了，文章学习时长那里只能拿4分了。可能是因为反复打开同一篇文章？

**Comment by CN1984** [comment]
Duplicate of #43
