### ISSUE TITLE
[IDEA] Maybe blocked again

### ISSUE THREAD

**Issue by xxwxxn** [CN1984/LearningThePooh#48]
From June,6th, it can not detect the time that needs to be studied, just tell "学习完毕，明天见“，actually we have not begin to study yet.

**Comment by 2ndMessiah** [comment]
Plz polish your sentences a bit. Working all fine here but with a total score up to 25 per day, whereas a temporary solution has been given by the author.

**Comment by CN1984** [comment]
Show me more details.

**Comment by 2ndMessiah** [comment]
> Show me more details.

mine works fine. the browser window automatically closes when the task is finished. on vivaldi 2.5 based on chromium 74.0.3729.172

**Comment by xxwxxn** [comment]
> Show me more details.

Sorry I update to the newest verion 1.4.2, and test it on MacOS in 360 Browser ver.69, it's OK now. In that morning Jun 6th,  I started learning at 8:30, in windows 360 Browser ver69, when I click the button, it jast flash for a moment and tells "xue xi wan bi".  Actually it didn't start learning at all. I'll have more test in the next week.
