### ISSUE TITLE
[BUG]视频没法播放

### ISSUE THREAD

**Issue by Phishion** [CN1984/LearningThePooh#49]
页面的是黑的，视频区域显示“请点击安装Adobe Flash player”，对应网址是 xuexi.1905.com/vod/play/85673.shtml
不是播放所有视频都出问题，就是上面这样的，如果随机到就会假死，分数也不会涨

**Device (please complete the following information):**
1.4,1 版本 Chrome

**Comment by 2ndMessiah** [comment]
Try adding the domain above to flash enabled site list in chrome://settings/content/flash?search=flash

**Comment by CN1984** [comment]
Duplicate of #55
