### ISSUE TITLE
[NOTICE]Chrome web store can not be update new version at present

### ISSUE THREAD

**Issue by CN1984** [CN1984/LearningThePooh#51]
![2019-06-24 092633](https://user-images.githubusercontent.com/47753275/59985632-539a5f80-9665-11e9-9265-39744c82de75.png)

May be this extension has been malicious reported in the chrome web store, the new version v1.4.2 has been in the "pending review" state for 2 days.

Try `load unpacked extension` to update the new version if you still want to use chrome,

**Comment by twinfishxixi** [comment]
We must keep learning, and No one can stop me !!! hahahahaha……

Thx a lot !

**Comment by LevineWoo** [comment]
再提交一个新的吧。。？这会卡在那过不了的。

**Comment by CN1984** [comment]
> 再提交一个新的吧。。？这会卡在那过不了的。

![2019-06-27 101233](https://user-images.githubusercontent.com/47753275/60228126-3a431e80-98c4-11e9-9ee1-d2dae201fa1c.png)

**Comment by LevineWoo** [comment]
> > 再提交一个新的吧。。？这会卡在那过不了的。
> 
> ![2019-06-27 101233](https://user-images.githubusercontent.com/47753275/60228126-3a431e80-98c4-11e9-9ee1-d2dae201fa1c.png)

感谢辛勤付出，已在商店更新1.4.2了
