### ISSUE TITLE
[IDEA] Mobile Firefox QR code logging. 

### ISSUE THREAD

**Issue by 2ndMessiah** [CN1984/LearningThePooh#53]
It seems only dingtalk account logging is supported in the mobile side at present. However, many ppls' account is registered by the phone number instead of dingtalk account. Adding logging status cookie detection of xuexi.cn will do as well.(users mannually scanning the qrcode of xuexi.cn to log in)

**Comment by noway2014** [comment]
Newly registered account, can't use diindind account, so can't use bear, what should I do?

**Comment by CN1984** [comment]
Next version will give a choose.

**Comment by CN1984** [comment]
Try version v1.4.4
