### ISSUE TITLE
[BUG]如果视频跳到m1905电影网，似乎会不计入视频个数和时间，也不能再跳转到其他学习页面，完全卡在那里了。求验证。

### ISSUE THREAD

**Issue by lifewinnerP11** [CN1984/LearningThePooh#55]
**Describe the bug**

**Device (please complete the following information):**
 - OS: [e.g. Windows 10, iOS8.1]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. v1.3.5, v1.3.6]

**Comment by CN1984** [comment]
Try version v1.4.4
