### ISSUE TITLE
卡在登陆界面

### ISSUE THREAD

**Issue by Willian-L** [CN1984/LearningThePooh#57]
打开后点击APP扫码或者钉钉账号登陆都没有反应

**Comment by CN1984** [comment]
Press F12 then copy the messages in `Console` to me.

**Comment by Willian-L** [comment]
你好！我打开学习小熊后点击F12没有反应，我使用的是QQ浏览器。但在Google浏览器上使用正常，而且点击F12可以打开控制面板。




------------------ 原始邮件 ------------------
发件人: "CN1984"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 下午3:16
收件人: "CN1984/LearningThePooh"<LearningThePooh@noreply.github.com>; 
抄送: "羽丶"<307813163@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CN1984/LearningThePooh] 卡在登陆界面 (#57)




Press F12 then copy the messages in Console to me.

**Comment by sylardct** [comment]
已被封号。。。

**Comment by ksky521** [comment]
![image](https://user-images.githubusercontent.com/1073262/62433919-041d7800-b769-11e9-85ae-656a07db1e0b.png)

**Comment by CN1984** [comment]
Duplicate of #60
