### ISSUE TITLE
点击后直接提示学习完成

### ISSUE THREAD

**Issue by bjznl** [CN1984/LearningThePooh#6]
今早使用时点击以后同时出现了学习中和学习完成的提示，登录窗口也闪退了。
![QQ截图20190322075614](https://user-images.githubusercontent.com/32454911/54792218-290cc500-4c78-11e9-843d-e74cbf570ce8.jpg)

**Comment by suchot** [comment]
在主页手动登录就可以正常学习了。 亲测可行

**Comment by bjznl** [comment]
> 在主页手动登录就可以正常学习了。 亲测可行

你的意思是手工到xuexi.cn后登陆，再点击小熊吗？我按这个方法还是同时出现2个提示

**Comment by CN1984** [comment]
The API about login status had been changed, waiting next version.

**Comment by bjznl** [comment]
> The API about login status had been changed, waiting next version.

ok,thx
