### ISSUE TITLE
貌似卡在登陆页面

### ISSUE THREAD

**Issue by bjznl** [CN1984/LearningThePooh#7]
点击icon后跳转到登录页面，但是标题栏始终显示login而且是读取的状态，手动打开网址登录一切正常

**Comment by CN1984** [comment]
> 点击icon后跳转到登录页面，但是标题栏始终显示login而且是读取的状态，手动打开网址登录一切正常

This issue cannot be reproduced on my device, can you provide the URLs from different situations?

**Comment by bjznl** [comment]
> > 点击icon后跳转到登录页面，但是标题栏始终显示login而且是读取的状态，手动打开网址登录一切正常
> 
> This issue cannot be reproduced on my device, can you provide the URLs from different situations?

明天早上我再测试一下，谢谢

**Comment by bjznl** [comment]
> > 点击icon后跳转到登录页面，但是标题栏始终显示login而且是读取的状态，手动打开网址登录一切正常
> 
> This issue cannot be reproduced on my device, can you provide the URLs from different situations?

测试了一下，是我的问题，谢谢了~另外，积分规则变了，学习最多只能获取到25分了。

**Comment by CN1984** [comment]
> 测试了一下，是我的问题，谢谢了~另外，积分规则变了，学习最多只能获取到25分了。

Cherish what you have at the moment... Maybe '20 points' coming soon.
